from __future__ import annotations

import io
import math
import os
import re
from datetime import datetime, timezone

import qrcode
from reportlab.lib.pagesizes import A4
from reportlab.lib.utils import ImageReader
from reportlab.pdfgen import canvas

from sqlalchemy.orm import Session

from app.core.config import settings
from app.models.booking import Booking
from app.models.time_entry import TimeEntry
from app.models.route import Route
from app.models.passenger import Passenger
from app.models.user import User


# Check-in & notes text (exact as per reference PDF)
CHECKIN_NOTES = """• A valid government-issued photo ID is required at check-in, and passengers must arrive 30 minutes before departure.
• Children under 16 must travel with an accompanying adult; passengers aged 2+ require their own seat.
• Passenger weight limits apply and must be accurately disclosed during booking.
• Baggage allowance is 10 kg per passenger (soft bags preferred).
• Flights are subject to weather, air traffic, and operational conditions; the pilot's decision is final.
• Intoxicated or disruptive passengers may be denied boarding; medical conditions must be declared in advance.
• For booking changes, contact support within 24 hours of your booking."""


def _resolve_ticket_template_path() -> str | None:
    """Path to ticket_template.pdf (exact design). If present, tickets are generated by overlaying data on this PDF."""
    path = (getattr(settings, "TICKET_TEMPLATE_PDF_PATH", None) or "").strip()
    if not path:
        _app_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        path = os.path.abspath(os.path.join(_app_root, "assets", "ticket_template.pdf"))
    elif not os.path.isabs(path):
        _project_root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
        path = os.path.normpath(os.path.join(_project_root, path))
    return path if os.path.isfile(path) else None


def _resolve_ticket_logo_path(which: str) -> str | None:
    """Resolve path to header or footer logo. Returns path if file exists, else None."""
    assert which in ("header", "footer")
    path = (getattr(settings, f"TICKET_{which.upper()}_LOGO_PATH", None) or "").strip()
    if not path:
        _app_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        path = os.path.abspath(os.path.join(_app_root, "assets", f"ticket_{which}_logo.png"))
    elif not os.path.isabs(path):
        _project_root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
        path = os.path.normpath(os.path.join(_project_root, path))
    return path if os.path.isfile(path) else None


def _draw_flysunbird_header_logo(c: canvas.Canvas, x: float, y_top: float, max_height: float = 32) -> float:
    """Draw FlySunbird logo (wing + 'fly' + 'SunBird' + tagline) with ReportLab. Returns height used."""
    orange = (0.92, 0.55, 0.15)
    red = (0.6, 0.12, 0.18)
    grey = (0.35, 0.35, 0.35)
    font_main = "Helvetica-Bold"
    size_main = 14
    size_tag = 7
    wing_w = 20
    gap = 4
    c.saveState()
    # Wing: simple upward curved stroke (left of text)
    c.setStrokeColorRGB(*orange)
    c.setLineWidth(2)
    c.setLineCap(1)
    c.setLineJoin(1)
    x0, y0 = x, y_top - max_height + 6
    # Bezier: start (x0,y0), controls (x0+2,y0+8), (x0+wing_w-2,y0+18), end (x0+wing_w,y0+20)
    # Canvas does not support moveTo/curveTo directly; use bezier().
    c.bezier(x0, y0, x0 + 2, y0 + 8, x0 + wing_w - 2, y0 + 18, x0 + wing_w, y0 + 20)
    # "fly" in orange, then "SunBird" in red
    tx = x + wing_w + gap
    ty = y_top - 10
    c.setFillColorRGB(*orange)
    c.setFont(font_main, size_main)
    c.drawString(tx, ty, "fly")
    fly_w = c.stringWidth("fly", font_main, size_main)
    c.setFillColorRGB(*red)
    c.drawString(tx + fly_w, ty, "SunBird")
    # Tagline below
    c.setFillColorRGB(*grey)
    c.setFont("Helvetica", size_tag)
    c.drawString(tx, ty - 11, "A unique experience...")
    c.restoreState()
    return max_height


def _draw_flysunbird_footer_design(
    c: canvas.Canvas, x_left: float, x_right: float, y_bottom: float, height: float
) -> None:
    """Draw footer: left = sunbird graphic + company/contact/address; right = red/pink/gold triangle pattern."""
    w = x_right - x_left
    y_top = y_bottom + height
    c.saveState()

    # ---- Left: bird graphic (simplified sunbird on branch) ----
    bx, by = x_left + 18, y_bottom + height - 22
    # Branch: brown line
    c.setStrokeColorRGB(0.45, 0.3, 0.2)
    c.setLineWidth(1.2)
    c.line(bx - 5, by - 2, bx + 28, by - 2)
    # Flowers: small red circles
    c.setFillColorRGB(0.85, 0.2, 0.2)
    for fx, fy in [(bx + 4, by + 1), (bx + 14, by + 2), (bx + 22, by)]:
        c.circle(fx, fy, 2.5, fill=1, stroke=0)
    # Bird body (ellipse-like path), yellow breast
    c.setFillColorRGB(0.98, 0.85, 0.25)
    c.setStrokeColorRGB(0.3, 0.25, 0.2)
    c.setLineWidth(0.5)
    c.ellipse(bx + 6, by - 1, bx + 20, by + 14, stroke=1, fill=1)
    # Head (blue-green)
    c.setFillColorRGB(0.2, 0.55, 0.6)
    c.circle(bx + 18, by + 12, 5, fill=1, stroke=0)
    # Beak
    c.setFillColorRGB(0.4, 0.3, 0.2)
    p = c.beginPath()
    p.moveTo(bx + 22, by + 11)
    p.lineTo(bx + 27, by + 10)
    p.lineTo(bx + 23, by + 9)
    p.close()
    c.drawPath(p, stroke=0, fill=1)

    # ---- Left: company and contact text ----
    tx = x_left
    ty = y_bottom + height - 38
    c.setFillColorRGB(0, 0, 0)
    c.setFont("Helvetica-Bold", 8)
    company = getattr(settings, "TICKET_FOOTER_COMPANY", "") or "Premier Air Limited t/a flySunBird"
    c.drawString(tx, ty, company[:50])
    c.setFont("Helvetica", 7)
    email = getattr(settings, "TICKET_FOOTER_EMAIL", "") or "booking@flysunbird.com"
    c.drawString(tx, ty - 8, f"Email: {email}"[:45])
    phone = getattr(settings, "TICKET_FOOTER_PHONE", "") or "+255 (0) 795 777 777"
    c.drawString(tx, ty - 16, f"Mobile: {phone}"[:45])
    # Map pin (small yellow diamond/circle)
    c.setFillColorRGB(0.98, 0.88, 0.35)
    c.circle(tx + 4, ty - 26, 3, fill=1, stroke=0)
    addr1 = getattr(settings, "TICKET_FOOTER_ADDRESS_LINE1", "") or "3rd Floor, De Ocean Plaza, Masaki."
    addr2 = getattr(settings, "TICKET_FOOTER_ADDRESS_LINE2", "") or "Dar es Salaam, United Republic of Tanzania"
    c.setFillColorRGB(0, 0, 0)
    c.drawString(tx + 10, ty - 25, addr1[:48])
    c.drawString(tx + 10, ty - 32, addr2[:48])

    # ---- Right: tessellating triangles (red, pink, gold, white) fading to top-left ----
    side = 7
    h_tri = side * math.sqrt(3) / 2
    red = (0.6, 0.12, 0.2)
    pink = (0.88, 0.55, 0.6)
    gold = (0.92, 0.72, 0.4)
    white = (1.0, 1.0, 1.0)
    colors = [red, pink, gold, white]
    # Pattern fills right portion; start from right edge
    x0 = x_right - (w * 0.45)
    y0 = y_bottom
    row = 0
    while y0 < y_top + h_tri:
        for col in range(35):
            x = x0 - row * (side / 2) + col * side
            if x > x_right + side:
                break
            # Fade: bottom-right = red/gold (idx 0,1), top-left = pink/white (idx 2,3)
            nx = (x - x_left) / w if w > 0 else 0
            ny = (y0 - y_bottom) / height if height > 0 else 0
            t = max(0, min(1, 1.0 - 0.5 * nx - 0.5 * ny))
            idx = min(3, int(t * 4))
            c.setFillColorRGB(*colors[idx])
            c.setStrokeColorRGB(*colors[idx])
            p = c.beginPath()
            if row % 2 == 0:
                # Base-down triangle
                p.moveTo(x, y0)
                p.lineTo(x + side, y0)
                p.lineTo(x + side / 2, y0 + h_tri)
            else:
                # Base-up triangle (base at y0+h_tri, peak at y0)
                p.moveTo(x, y0 + h_tri)
                p.lineTo(x + side, y0 + h_tri)
                p.lineTo(x + side / 2, y0)
            p.close()
            # No stroke to avoid seams; fill only.
            c.drawPath(p, stroke=0, fill=1)
        y0 += h_tri
        row += 1
    c.restoreState()


def _ticket_url(booking_ref: str) -> str:
    base = (getattr(settings, "API_PUBLIC_URL", None) or "").strip().rstrip("/")
    if not base:
        base = "http://localhost:8000"
    return f"{base}/api/v1/public/bookings/{booking_ref}/ticket"


def _make_qr_image_bytes(url: str, box_size: int = 3, border: int = 2) -> bytes:
    qr = qrcode.QRCode(version=1, box_size=box_size, border=border, error_correction=qrcode.constants.ERROR_CORRECT_M)
    qr.add_data(url)
    qr.make(fit=True)
    img = qr.make_image(fill_color="black", back_color="white")
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    buf.seek(0)
    return buf.read()


def _footer2_experience(k: dict) -> str:
    """Format footer line 2 exactly as standard: 'Route → To • Seats: N • Type duration min'."""
    route = f"{k.get('route_from') or ''} → {k.get('route_to') or ''}".strip()
    pax = k.get("pax") or 0
    exp = (k.get("experience") or "").strip()
    # Standard shows e.g. "Scenic 30 min" — extract "N Minutes Type." -> "Type N min"
    m = re.match(r"(\d+)\s*Minutes\s*(.+)", exp, re.IGNORECASE)
    if m:
        duration, rest = m.group(1), m.group(2).rstrip(".").strip()
        exp_short = f"{rest} {duration} min"
    else:
        exp_short = exp.split(".")[0][:25] if exp else ""
    return f"{route} • Seats: {pax} • {exp_short}"[:70]


def _duration_minutes(start: str, end: str) -> int:
    """Parse HH:MM start/end and return duration in minutes."""
    def to_mins(s: str) -> int:
        s = (s or "").strip()
        m = re.match(r"(\d{1,2}):(\d{2})", s)
        if m:
            return int(m.group(1)) * 60 + int(m.group(2))
        return 0
    return max(0, to_mins(end) - to_mins(start))


def _format_time_12h(hhmm: str) -> str:
    """Format HH:MM as 11:00 AM."""
    s = (hhmm or "").strip()
    m = re.match(r"(\d{1,2}):(\d{2})", s)
    if not m:
        return s or "—"
    h, mi = int(m.group(1)), int(m.group(2))
    if h == 0:
        return f"12:{mi:02d} AM"
    if h < 12:
        return f"{h}:{mi:02d} AM"
    if h == 12:
        return f"12:{mi:02d} PM"
    return f"{h - 12}:{mi:02d} PM"


def build_ticket_context(db: Session, b: Booking) -> dict | None:
    """Build ticket context from booking for PDF render. Returns dict for render_ticket_pdf_bytes or None."""
    te = db.get(TimeEntry, b.time_entry_id)
    if not te:
        return None
    route = db.get(Route, te.route_id) if te.route_id else None
    route_from = route.from_label if route else "—"
    route_to = route.to_label if route else "—"
    first_passenger = db.query(Passenger).filter(Passenger.booking_id == b.id).order_by(Passenger.created_at.asc()).first()
    passenger_name = f"{(first_passenger.first or '').strip()} {(first_passenger.last or '').strip()}".strip() if first_passenger else ""
    passenger_phone = (first_passenger.phone or "").strip() if first_passenger else ""
    booker = db.get(User, b.user_id) if b.user_id else None
    booker_email = (booker.email or "").strip() if booker else ""
    duration_min = _duration_minutes(te.start or "", te.end or "")
    experience = f"{duration_min} Minutes {(te.cabin or 'Helicopter Scenic').strip()}."
    aircraft_type = (getattr(te, "aircraft_type", None) or "").strip()
    departure_location = (getattr(te, "departure_location", None) or "").strip() or route_from
    amount_usd = int(getattr(b, "total_usd", 0) or 0)
    amount_tzs = int(getattr(b, "total_tzs", 0) or 0)
    currency = (getattr(b, "currency", None) or "USD").strip()
    return {
        "booking_ref": b.booking_ref,
        "passenger_name": passenger_name or "(Not provided)",
        "passenger_phone": passenger_phone,
        "booker_email": booker_email,
        "route_from": route_from,
        "route_to": route_to,
        "date_str": te.date_str or "",
        "start_time": te.start or "",
        "end_time": te.end or "",
        "pax": int(b.pax),
        "payment_status": b.payment_status or "unpaid",
        "flight_no": (te.flight_no or "").strip(),
        "experience": experience,
        "aircraft_type": aircraft_type,
        "departure_location": departure_location,
        "amount_usd": amount_usd,
        "amount_tzs": amount_tzs,
        "currency": currency,
    }


# Positions on ticket_template.pdf — exact bboxes from standard PDF so overlay matches "exactly as is".
# Each: (name, (x0, y0, x1, y1), value_getter). Text is inserted at (x0, y0 + baseline).
_TEMPLATE_FIELDS = [
    # Status header: "PAID • CONFIRMED" or "UNPAID"
    ("status_header", (90, 87.6, 179.8, 98.7), lambda k: "PAID • CONFIRMED" if (k.get("payment_status") or "").lower() == "paid" else "UNPAID"),
    ("booking_ref", (148.2, 179.7, 200.1, 190.7), lambda k: (k.get("booking_ref") or "")[:20]),
    ("status", (380.8, 179.7, 405.8, 190.7), lambda k: "PAID" if (k.get("payment_status") or "").lower() == "paid" else "UNPAID"),
    ("passenger_name", (148.2, 205.5, 191.2, 216.5), lambda k: (k.get("passenger_name") or "Passenger")[:25]),
    ("contact", (380.8, 205.5, 558.8, 216.5), lambda k: ((k.get("passenger_phone") or "") + " / " + (k.get("booker_email") or "")).strip(" / ")[:55]),
    # Route: two lines as on standard — "From →" then "To"
    ("route_line1", (148.2, 244.3, 256.4, 255.3), lambda k: ((k.get("route_from") or "") + " →")[:35]),
    ("route_line2", (148.2, 257.7, 185.9, 268.7), lambda k: (k.get("route_to") or "")[:20]),
    ("experience", (380.8, 244.3, 519.0, 255.3), lambda k: (k.get("experience") or "")[:45]),
    ("date", (148.2, 283.0, 200.8, 294.1), lambda k: (k.get("date_str") or "")[:12]),
    ("departure_time", (380.8, 283.0, 427.5, 294.1), lambda k: _format_time_12h(k.get("start_time") or "")[:10]),
    ("aircraft_type", (148.2, 308.8, 206.8, 319.9), lambda k: (k.get("aircraft_type") or "")[:20]),
    ("departure_location", (380.8, 308.8, 455.0, 319.9), lambda k: (k.get("departure_location") or "")[:25]),
    ("pax", (148.2, 347.6, 183.1, 358.6), lambda k: f"{k.get('pax') or 0} Seats"),
    # Amount: single number as on standard (e.g. "500")
    ("amount", (380.8, 347.6, 400.0, 358.6), lambda k: str(k.get("amount_usd") or k.get("amount_tzs") or 0)),
    ("footer1", (102.6, 547.3, 467.5, 558.3), lambda k: f"{k.get('booking_ref')} • {(k.get('passenger_name') or 'Passenger')[:20]} • {k.get('date_str')} • {(k.get('start_time') or '').strip() or '—'}"[:70]),
    ("footer2", (102.6, 560.5, 520, 573), lambda k: _footer2_experience(k)),
]


def _render_ticket_pdf_from_template(
    *,
    booking_ref: str,
    passenger_name: str,
    passenger_phone: str = "",
    booker_email: str = "",
    route_from: str,
    route_to: str,
    date_str: str,
    start_time: str,
    end_time: str,
    pax: int,
    payment_status: str,
    flight_no: str = "",
    experience: str = "",
    aircraft_type: str = "",
    departure_location: str = "",
    amount_usd: int = 0,
    amount_tzs: int = 0,
    currency: str = "USD",
) -> bytes:
    """Generate ticket by overlaying variable data on ticket_template.pdf. Preserves exact design (logos, footer)."""
    import fitz  # PyMuPDF

    template_path = _resolve_ticket_template_path()
    if not template_path:
        raise FileNotFoundError("ticket_template.pdf not found")
    ctx = {
        "booking_ref": booking_ref,
        "passenger_name": passenger_name,
        "passenger_phone": passenger_phone,
        "booker_email": booker_email,
        "route_from": route_from,
        "route_to": route_to,
        "date_str": date_str,
        "start_time": start_time,
        "pax": pax,
        "payment_status": payment_status,
        "experience": experience,
        "aircraft_type": aircraft_type,
        "departure_location": departure_location,
        "amount_usd": amount_usd,
        "amount_tzs": amount_tzs,
    }
    doc = fitz.open(template_path)
    page = doc[0]
    for _name, (x0, y0, x1, y1), get_val in _TEMPLATE_FIELDS:
        val = get_val(ctx)
        if not val:
            continue
        rect = fitz.Rect(x0, y0, x1, y1)
        shape = page.new_shape()
        shape.draw_rect(rect)
        shape.finish(fill=(1, 1, 1), color=(1, 1, 1))
        shape.commit()
        # Baseline at bottom of bbox so text sits exactly as in standard PDF
        page.insert_text((x0, y1 - 2), str(val)[:80], fontsize=10, fontname="helv")
    # QR code for ticket URL (overlay on template)
    try:
        ticket_url = _ticket_url(booking_ref)
        qr_bytes = _make_qr_image_bytes(ticket_url, box_size=2, border=1)
        qr_rect = fitz.Rect(500, 430, 578, 508)
        shape = page.new_shape()
        shape.draw_rect(qr_rect)
        shape.finish(fill=(1, 1, 1), color=(1, 1, 1))
        shape.commit()
        page.insert_image(qr_rect, stream=qr_bytes)
    except Exception:
        pass
    buf = io.BytesIO()
    doc.save(buf, deflate=True)
    doc.close()
    return buf.getvalue()


def render_ticket_pdf_bytes(
    *,
    booking_ref: str,
    passenger_name: str,
    passenger_phone: str = "",
    booker_email: str = "",
    route_from: str,
    route_to: str,
    date_str: str,
    start_time: str,
    end_time: str,
    pax: int,
    payment_status: str,
    flight_no: str = "",
    experience: str = "",
    aircraft_type: str = "",
    departure_location: str = "",
    amount_usd: int = 0,
    amount_tzs: int = 0,
    currency: str = "USD",
) -> bytes:
    """Render ticket PDF: from template if ticket_template.pdf exists, else drawn layout."""
    template_path = _resolve_ticket_template_path()
    if template_path:
        try:
            return _render_ticket_pdf_from_template(
                booking_ref=booking_ref,
                passenger_name=passenger_name,
                passenger_phone=passenger_phone,
                booker_email=booker_email,
                route_from=route_from,
                route_to=route_to,
                date_str=date_str,
                start_time=start_time,
                end_time=end_time,
                pax=pax,
                payment_status=payment_status,
                flight_no=flight_no,
                experience=experience,
                aircraft_type=aircraft_type,
                departure_location=departure_location,
                amount_usd=amount_usd,
                amount_tzs=amount_tzs,
                currency=currency,
            )
        except Exception:
            pass  # fallback to drawn
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    w, h = A4
    margin = 40
    x_left = margin
    x_right = w - margin
    y = h - margin

    # ----- Header logo (drawn: wing + flySunBird + tagline) -----
    logo_header_path = _resolve_ticket_logo_path("header")
    if logo_header_path:
        try:
            img_reader = ImageReader(logo_header_path)
            iw, ih = img_reader.getSize()
            max_logo_h = 36
            scale = min(1.0, max_logo_h / ih) if ih else 1.0
            draw_w, draw_h = iw * scale, ih * scale
            c.drawImage(img_reader, x_left, y - draw_h, width=draw_w, height=draw_h)
            y -= draw_h + 12
        except Exception:
            pass
    else:
        logo_h = _draw_flysunbird_header_logo(c, x_left, y, max_height=32)
        y -= logo_h + 12

    is_paid = (payment_status or "").lower() == "paid"
    status_header = "PAID • CONFIRMED" if is_paid else "UNPAID"
    status_line2 = "PAID" if is_paid else "UNPAID"

    # ----- Status header -----
    c.setFont("Helvetica-Bold", 16)
    c.drawString(x_left, y, status_header)
    y -= 28

    # ----- BOOKING SUMMARY -----
    c.setFont("Helvetica-Bold", 12)
    c.drawString(x_left, y, "BOOKING SUMMARY")
    y -= 20

    c.setFont("Helvetica", 10)
    c.drawString(x_left, y, f"Booking Ref: {booking_ref}")
    c.drawString(x_right - 80, y, f"Status: {status_line2}")
    y -= 18

    c.drawString(x_left, y, "Passenger")
    y -= 14
    c.drawString(x_left, y, f"Name: {passenger_name or '(Not provided)'}")
    y -= 14
    contact = [s for s in [passenger_phone, booker_email] if s]
    c.drawString(x_left, y, f"Phone/Email: {' / '.join(contact) if contact else '—'}")
    y -= 22

    c.drawString(x_left, y, f"Flight Route: {route_from} → {route_to}")
    y -= 14
    if experience:
        c.drawString(x_left, y, f"Experience: {experience}")
        y -= 14
    c.drawString(x_left, y, f"Date: {date_str}")
    c.drawString(x_left + 200, y, f"Departure Time: {_format_time_12h(start_time)}")
    y -= 14
    if aircraft_type:
        c.drawString(x_left, y, f"Aircraft Type: {aircraft_type}")
        y -= 14
    if departure_location:
        c.drawString(x_left, y, f"Departure Location: {departure_location}")
        y -= 14
    c.drawString(x_left, y, f"Pax: {pax} Seats")
    if amount_usd and amount_tzs:
        c.drawString(x_left + 180, y, f"Amount (USD/TZS): {amount_usd} / {amount_tzs}")
    elif amount_tzs:
        c.drawString(x_left + 180, y, f"Amount (TZS): {amount_tzs}")
    else:
        c.drawString(x_left + 180, y, f"Amount (USD): {amount_usd or 0}")
    y -= 24

    # ----- BANK INFORMATION (unpaid only) -----
    if not is_paid:
        c.setFont("Helvetica-Bold", 11)
        c.drawString(x_left, y, "BANK INFORMATION")
        y -= 16
        c.setFont("Helvetica", 10)
        bank_name = getattr(settings, "BANK_NAME", "") or "CRDB BANK"
        bank_acc = getattr(settings, "BANK_ACCOUNT_NAME", "") or "PREMIER AIR LIMITED"
        bank_usd = getattr(settings, "BANK_ACCOUNT_USD", "") or "0250000WKYA00"
        bank_tzs = getattr(settings, "BANK_ACCOUNT_TZS", "") or "0150000WKYA00"
        bank_branch = getattr(settings, "BANK_BRANCH", "") or "Palm Beach, Dar es Salaam, Tanzania"
        bank_swift = getattr(settings, "BANK_SWIFT", "") or "CORUTZTZXXX"
        c.drawString(x_left, y, f"• Bank Name: {bank_name}")
        y -= 14
        c.drawString(x_left, y, f"• Account Name (ACC NAME): {bank_acc}")
        y -= 14
        c.drawString(x_left, y, "• Account Numbers")
        y -= 14
        c.drawString(x_left, y, f"• USD - {bank_usd}")
        y -= 14
        c.drawString(x_left, y, f"• TZS - {bank_tzs}")
        y -= 14
        c.drawString(x_left, y, f"• Branch Name: {bank_branch}")
        y -= 14
        c.drawString(x_left, y, f"• SWIFT Code: {bank_swift}")
        y -= 24

    # ----- Check-in & notes -----
    c.setFont("Helvetica-Bold", 11)
    c.drawString(x_left, y, "Check-in & notes")
    y -= 16
    c.setFont("Helvetica", 9)
    for line in CHECKIN_NOTES.split("\n"):
        if line.strip():
            c.drawString(x_left, y, line.strip()[:90])
            y -= 12
    y -= 16

    # ----- Scan for details + QR -----
    c.setFont("Helvetica", 10)
    c.drawString(x_left, y, "Scan for details")
    y -= 10
    try:
        ticket_url = _ticket_url(booking_ref)
        qr_png = _make_qr_image_bytes(ticket_url, box_size=2, border=1)
        img = ImageReader(io.BytesIO(qr_png))
        qr_size = 80
        qr_x = x_right - qr_size
        qr_y = y - qr_size
        c.drawImage(img, qr_x, qr_y, width=qr_size, height=qr_size)
    except Exception:
        pass
    y -= 20

    # ----- Footer: line, then branding block at bottom -----
    c.setStrokeColorRGB(0.75, 0.75, 0.75)
    c.setLineWidth(0.5)
    c.line(x_left, y, x_right, y)
    c.setStrokeColorRGB(0, 0, 0)
    y -= 14

    logo_footer_path = _resolve_ticket_logo_path("footer")
    if logo_footer_path:
        try:
            img_reader = ImageReader(logo_footer_path)
            iw, ih = img_reader.getSize()
            max_footer_h = 24
            scale = min(1.0, max_footer_h / ih) if ih else 1.0
            draw_w, draw_h = iw * scale, ih * scale
            c.drawImage(img_reader, x_left, y - draw_h, width=draw_w, height=draw_h)
            y -= draw_h + 8
        except Exception:
            pass

    # Footer branding band height; footer text sits just above it, "Generated" at very bottom
    footer_design_height = 50
    footer_text_y1 = footer_design_height + 10
    footer_text_y2 = footer_design_height
    generated_y = 6

    # Drawn footer design (sunbird + company/address left, triangle pattern right)
    _draw_flysunbird_footer_design(c, x_left, x_right, 0, footer_design_height)

    # ----- Footer text (above the design) -----
    exp_short = (experience or "").split(".")[0].strip() or "Scenic"
    footer = f"{booking_ref} • {passenger_name or 'Passenger'} • {date_str} • {start_time}"
    c.setFont("Helvetica", 8)
    c.setFillColorRGB(0, 0, 0)
    c.drawString(x_left, footer_text_y1, footer[:95])
    c.drawString(x_left, footer_text_y2, f"{route_from} → {route_to} • Seats: {pax} • {exp_short}")

    c.setFont("Helvetica", 7)
    c.setFillColorRGB(0.5, 0.5, 0.5)
    c.drawString(x_left, generated_y, f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}")
    c.setFillColorRGB(0, 0, 0)

    c.showPage()
    c.save()
    return buf.getvalue()


def store_ticket_pdf(*, booking_ref: str, pdf_bytes: bytes) -> tuple[str, str]:
    if settings.GCS_BUCKET_NAME and settings.GOOGLE_APPLICATION_CREDENTIALS:
        try:
            from google.cloud import storage  # type: ignore
        except Exception as e:
            raise RuntimeError("google-cloud-storage is not installed. Install requirements and retry") from e
        client = storage.Client()
        bucket = client.bucket(settings.GCS_BUCKET_NAME)
        object_key = f"tickets/{booking_ref}.pdf"
        blob = bucket.blob(object_key)
        blob.upload_from_string(pdf_bytes, content_type="application/pdf")
        return "gcs", object_key
    base = settings.TICKET_LOCAL_DIR or "./data/tickets"
    os.makedirs(base, exist_ok=True)
    object_key = os.path.join(base, f"{booking_ref}.pdf")
    with open(object_key, "wb") as f:
        f.write(pdf_bytes)
    return "local", object_key


def load_ticket_pdf_bytes(*, booking_ref: str, storage: str, object_key: str) -> bytes | None:
    if not object_key:
        return None
    try:
        if storage == "gcs":
            if not getattr(settings, "GCS_BUCKET_NAME", None):
                return None
            try:
                from google.cloud import storage  # type: ignore
            except Exception:
                return None
            client = storage.Client()
            bucket = client.bucket(settings.GCS_BUCKET_NAME)
            blob = bucket.blob(object_key)
            return blob.download_as_bytes()
        path = object_key
        if not os.path.isabs(path):
            base = getattr(settings, "TICKET_LOCAL_DIR", None) or "./data/tickets"
            path = os.path.join(base, os.path.basename(path))
        if not os.path.isfile(path):
            return None
        with open(path, "rb") as f:
            return f.read()
    except Exception:
        return None
